### PR TITLE
Rename to LibreFanControl via sed replacing

### PR DESCRIPTION
**Pull request by zhangjing-GitHub-Code**
Replaced by Git Bash 'sed' and find.
I replaced in every file and rename the `FanControl` DIR.
If there's things will make code **wrong**, you can check.
Merge as your opinion, thanks.

### CODE REVIEW

**Comment by wiiznokes** [comment]
Thanks, this seems fine to me. 

I think there is still a problem with this line in `CI/build_windows.sh` (need LibreFanControl instead).
`cp ./FanControl/app/build/compose/binaries/main-release/msi/LibreFanControl* ./publish`

Also, this shows that we need to verify that each build command went well. Maybe with
```
if [[ $? -ne 0 ]]; then
    exit 1
fi
```

**Comment by wiiznokes** [comment]
in fact, just `set -e` on top of each script will do the tricks

**Comment by zhangjing-GitHub-Code** [comment]
Yeah,,,, sed seems like only replace once in 1 line, and I didn't let replace multiple times...

**Comment by wiiznokes** [comment]
okay seems good, will merge

**Pull request merged**
