### PR TITLE
Translate to Chinese Simplified and a workflow CI

### PR DESCRIPTION
**Pull request by zhangjing-GitHub-Code**
Hello.
I translated the language to zh_cn, by copying `strings-en.json` to `strings-zh_cn.json`, and translate contents in it.
I also added `"zh_cn": "简体中文"` in other two json.
If language changing needs change code, pls u do that.

I also add a actions workflow, uploads published windows msi to artifacts.
Merge this and modify if you want, thanks.

### CODE REVIEW

**Comment by zhangjing-GitHub-Code** [comment]
Ok I added enum for language, waiting for complie, you can see others(

**Comment by wiiznokes** [comment]
Hi, thank you very much for that !

Good to see more language translation added, although having string resources in json is more a workaround than a real solution.

And I'm a noobie with github workflows, I have some question about it
- Is it possible to test a workflow before merging ?
- From what I understand, the workflow in question allows you to build the windows package, but it will also be able to indicate if the build went well? Because otherwise, I don't really see the point, except if it allows you to create a release automatically, it could be interesting.
- And also, from what I know, it's not possible to build a Windows release with Linux, at least it doesn't work on my PC. Won't that be a problem with this workflow?

**Comment by zhangjing-GitHub-Code** [comment]
First, thanks.
I see you use **json strings** for language so I use it to translate.
If you have **better solution**, just say it.

Answers for your question(in fact I dont know workflows too much):
> * Is it possible to test a workflow before merging ?

Yes, just add `pull_request:` in `on` propertie in workflow yml.
(In my yml I added that but dont specfiy a branch.)
> * From what I understand, the workflow in question allows you to build the windows package, but it will also be able to indicate if the build went well? Because otherwise, I don't really see the point, except if it allows you to create a release automatically, it could be interesting.

I think github supports that and may saw repos uses check in pr, they will have things like 'Check passed'(?).
> * And also, from what I know, it's not possible to build a Windows release with Linux, at least it doesn't work on my PC. Won't that be a problem with this workflow?

Well, github workflow **can** set the OS of runner machine: `windows-latest`,`macos-latest`(?),`ubuntu-latest`(one linux distribution). I set `windows-latest` in my workflow.

You can look in [my fork](https://github.com/zhangjing-GitHub-Code/LibreFanControl-modpr) if you want :).
The github actions workflow yml files are in `.github/workflows/`.

If you have no prolem with my fork, u can merge it.

**Comment by zhangjing-GitHub-Code** [comment]
Now my workflow yml uses **your** CI/windows-publish.sh, U(or I) can put them **out in yml directly** and set a cache ? Now the build time is **about 7min**.

**Comment by zhangjing-GitHub-Code** [comment]
Just like this pr page, on the a bit top there's `Checks` tab, if u click in u will see it needs github action.

**Comment by wiiznokes** [comment]
Ok, I think the build workflow and scripts will need a bit of modification. I think I will create a dev branch while testing this. That way I could also add a build for Linux at the same time, and make sure it works as it should.

> Now my workflow yml uses your CI/windows-publish.sh, U(or I) can put them out in yml directly and set a cache ? Now the build time is about 7min.

What do you mean by put them out ? I think a cache will be great! Especially for Gradle dependencies and the JDK. Or even for the repo files.

**Comment by zhangjing-GitHub-Code** [comment]
Wait....
If you have time to test it,
you ~shuould~ should look into Actions tab and needs to enable it..(

**Comment by wiiznokes** [comment]
Done here: #94 .
There is a workflow to publish release now, I not tested it thought.
And also to build Linux appImage.
There is even a cache out of the box :smiley:

**Pull request merged**
